const SECONDS = 1000;
const MINUTES = SECONDS * 60;
const HOURS = MINUTES * 60;
const DAYS = HOURS * 24;

const REFRESH_RATE = 60; // units

const STARTING_BALANCE = 50;

export { SECONDS, MINUTES, HOURS, DAYS, REFRESH_RATE, STARTING_BALANCE };
